#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycv-deployment
spec:
  selector:
    matchLabels:
      app: mycv-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mycv-server
    spec:
      containers:
      - name: mycv-container
        #image: gcr.io/tensorflow-serving/resnet
        image: docker.io/iancarlo/mycvmat:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mycv-service
  name: mycv-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: mycv-server
  type: LoadBalancer
